/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 *
 * This source code is subject to the terms and conditions defined in the
 * file 'LICENSE' which is part of this source code package.
 *
 * Description:
 */
#ifndef AMLOGIC_PQCMD_H
#define AMLOGIC_PQCMD_H

typedef enum pqcmd_e {
    //PQ CMD(201~299)
    PQ_MODULE_CMD_START           = 200,
    PQ_SET_PICTURE_MODE           = 201,
    PQ_GET_PICTURE_MODE           = 202,
    PQ_SET_COLOR_TEMPERATURE_MODE = 203,
    PQ_GET_COLOR_TEMPERATURE_MODE = 204,
    PQ_SET_BRIGHTNESS             = 205,
    PQ_GET_BRIGHTNESS             = 206,
    PQ_SET_CONTRAST               = 207,
    PQ_GET_CONTRAST               = 208,
    PQ_SET_SATUATION              = 209,
    PQ_GET_SATUATION              = 210,
    PQ_SET_HUE                    = 211,
    PQ_GET_HUE                    = 212,
    PQ_SET_SHARPNESS              = 213,
    PQ_GET_SHARPNESS              = 214,
    PQ_SET_NOISE_REDUCTION_MODE   = 215,
    PQ_GET_NOISE_REDUCTION_MODE   = 216,
    PQ_SET_EYE_PROTECTION_MODE    = 217,
    PQ_GET_EYE_PROTECTION_MODE    = 218,
    PQ_SET_GAMMA                  = 219,
    PQ_GET_GAMMA                  = 220,
    PQ_SET_DISPLAY_MODE           = 221,
    PQ_GET_DISPLAY_MODE           = 222,
    PQ_SET_BACKLIGHT              = 223,
    PQ_GET_BACKLIGHT              = 224,
    PQ_SET_DYNAMICBACKLIGHT       = 225,
    PQ_GET_DYNAMICBACKLIGHT       = 226,
    PQ_SET_LOCALCONTRAST          = 227,
    PQ_GET_LOCALCONTRAST          = 228,
    PQ_SET_CM                     = 229,
    PQ_GET_CM                     = 230,
    PQ_SET_SOURCE_CHANNEL         = 231,
    PQ_GET_SOURCE_CHANNEL         = 232,
    PQ_SET_COLORGAMUT             = 233,
    PQ_GET_COLORGAMUT             = 234,
    PQ_GET_SOURCE_HDR_TYPE        = 235,
    PQ_SET_DYNAMICCONTRAST        = 236,
    PQ_GET_DYNAMICCONTRAST        = 237,
    PQ_SET_RECOVERYPQ             = 238,
    PQ_GET_HAS_MEMC               = 239,
    PQ_SET_MEMCMODE               = 240,
    PQ_GET_MEMCMODE               = 241,
    PQ_SET_MEMC_DEBLUR            = 242,
    PQ_GET_MEMC_DEBLUR            = 243,
    PQ_SET_MEMC_DEJUDDER          = 244,
    PQ_GET_MEMC_DEJUDDER          = 245,
    PQ_SET_DECONTOUR              = 246,
    PQ_GET_DECONTOUR              = 247,
    PQ_SET_DEBLOCK                = 248,
    PQ_GET_DEBLOCK                = 249,
    PQ_SET_DEMOSQUITO             = 250,
    PQ_GET_DEMOSQUITO             = 251,
    PQ_SET_BLACKSTRETCH           = 252,
    PQ_GET_BLACKSTRETCH           = 253,
    PQ_SET_BLUESTRETCH            = 254,
    PQ_GET_BLUESTRETCH            = 255,
    PQ_GET_HAS_AIPQ               = 256,
    PQ_SET_AIPQ                   = 257,
    PQ_GET_AIPQ                   = 258,
    PQ_GET_HAS_AISR               = 259,
    PQ_SET_AISR                   = 260,
    PQ_GET_AISR                   = 261,
    PQ_SET_LDIM                   = 262,
    PQ_GET_LDIM                   = 263,
    PQ_SET_MPEGNR                 = 264,
    PQ_GET_MPEGNR                 = 265,
    PQ_GET_COLORTEMP_USER_PARAM   = 266,
    PQ_SET_PICTURE_UI_CLEAR       = 267,
    PQ_SET_COLOR_CUSTOMIZE        = 268,
    PQ_GET_COLOR_CUSTOMIZE        = 269,
    PQ_SET_COLOR_CUSTOMIZE_3DLUT  = 270,
    PQ_GET_COLOR_CUSTOMIZE_3DLUT  = 271,
    PQ_RESET_COLOR_CUSTOMIZE      = 272,
    PQ_SET_WB_GAMMA_DATA          = 273,
    PQ_GET_WB_GAMMA_DATA          = 274,
    PQ_SET_SUPERRESOLUTION        = 275,
    PQ_GET_SUPERRESOLUTION        = 276,
    PQ_GET_LAST_PICTURE_MODE      = 277,
    PQ_SET_COLOR_CUSTOMIZE_ENABLE = 278,
    PQ_GET_COLOR_CUSTOMIZE_ENABLE = 279,
    PQ_GET_DB_VERSION_INFO        = 280,
    PQ_SET_WB_GAMMA_ENABLE        = 281,
    PQ_GET_WB_GAMMA_ENABLE        = 282,
    PQ_SET_WB_GAMMA_MODE          = 283,
    PQ_GET_WB_GAMMA_MODE          = 284,
    PQ_SET_HDR_TONE_MAPPING_MODE  = 285,
    PQ_GET_HDR_TONE_MAPPING_MODE  = 286,
    PQ_SET_FILM_MAKER_MODE        = 287,
    PQ_GET_FILM_MAKER_MODE        = 288,
    PQ_MODULE_CMD_MAX             = 299,

    //PQ factory(300~399)
    PQ_FACTORY_CMD_START                      = 300,
    PQ_FACTORY_RESET_PICTURE_MODE             = 301,
    PQ_FACTORY_RESET_COLOR_TEMPERATURE_MODE   = 302,
    PQ_FACTORY_SET_COLOR_TEMPERATURE_MODE     = 303,
    PQ_FACTORY_GET_COLOR_TEMPERATURE_MODE     = 304,
    PQ_FACTORY_SET_BRIGHTNESS                 = 305,
    PQ_FACTORY_GET_BRIGHTNESS                 = 306,
    PQ_FACTORY_SET_CONTRAST                   = 307,
    PQ_FACTORY_GET_CONTRAST                   = 308,
    PQ_FACTORY_SET_SATUATION                  = 309,
    PQ_FACTORY_GET_SATUATION                  = 310,
    PQ_FACTORY_SET_HUE                        = 311,
    PQ_FACTORY_GET_HUE                        = 312,
    PQ_FACTORY_SET_SHARPNESS                  = 313,
    PQ_FACTORY_GET_SHARPNESS                  = 314,
    PQ_FACTORY_SET_OVERSCAN                   = 315,
    PQ_FACTORY_GET_OVERSCAN                   = 316,
    PQ_FACTORY_SET_WB_RED_GAIN                = 317,
    PQ_FACTORY_GET_WB_RED_GAIN                = 318,
    PQ_FACTORY_SET_WB_GREEN_GAIN              = 319,
    PQ_FACTORY_GET_WB_GREEN_GAIN              = 320,
    PQ_FACTORY_SET_WB_BLUE_GAIN               = 321,
    PQ_FACTORY_GET_WB_BLUE_GAIN               = 322,
    PQ_FACTORY_SET_WB_RED_OFFSET              = 323,
    PQ_FACTORY_GET_WB_RED_OFFSET              = 324,
    PQ_FACTORY_SET_WB_GREEN_OFFSET            = 325,
    PQ_FACTORY_GET_WB_GREEN_OFFSET            = 326,
    PQ_FACTORY_SET_WB_BLUE_OFFSET             = 327,
    PQ_FACTORY_GET_WB_BLUE_OFFSET             = 328,
    PQ_FACTORY_SET_RGB_PATTERN                = 329,
    PQ_FACTORY_GET_RGB_PATTERN                = 330,
    PQ_FACTORY_SET_GRAY_PATTERN               = 331,
    PQ_FACTORY_GET_GRAY_PATTERN               = 332,
    PQ_FACTORY_SET_NOLINE_PARAMS              = 333,
    PQ_FACTORY_GET_NOLINE_PARAMS              = 334,
    PQ_FACTORY_SET_COLOR_PARAMS               = 335,
    PQ_FACTORY_GET_COLOR_PARAMS               = 336,
    PQ_FACTORY_SET_DEC_LUMA_PARAMS            = 337,
    PQ_FACTORY_GET_DEC_LUMA_PARAMS            = 338,
    PQ_FACTORY_GET_Sharpness_Params           = 339,
    PQ_FACTORY_SET_Sharpness_Params           = 340,
    PQ_FACTORY_SET_PQ_ENABLE                  = 341,
    PQ_FACTORY_GET_PQ_ENABLE                  = 342,
    PQ_FACTORY_SET_WB_GAMMA_DATA              = 343,
    PQ_FACTORY_GET_WB_GAMMA_DATA              = 344,

    PQ_FACTORY_CMD_MAX                        = 399,
}pqcmd_t;

#endif  //AMLOGIC_PQCMD_H
